# Generated by Django 5.2.4 on 2025-07-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_type',
            field=models.CharField(choices=[('best', 'best'), ('funny', 'funny'), ('creative', 'creative'), ('responsible', 'responsible'), ('lazy', 'lazy')], max_length=15),
        ),
    ]
